name: Mostrar hola
on: 
  push:
    branch: [ <rama> ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout del repositorio
      uses: actions/checkout@v3
    - name: Dar permisos de ejecuci√≥n
      run: chmod +x ./src/script.sh
    - name: Ejecutar script
      run: ./src/script.sh
  
